### ISSUE TITLE
Independent installation failing on Ubuntu

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-utilities#87]
Steps to reproduce:

1. Create a new EC2 Ubuntu instance. 
2. sudo apt update
3. sudo apt upgrade
4. git clone https://github.com/beckn/beckn-utilities.git
5. cd beckn-utilities/onix
6. ./start_beckn_v2.sh
7. Choose n for all components
8. Choose 1 for installing gateway and registry

It gives the following error:
```
Enter your choice (1-6): 1
................Installing required packages................
Docker is already installed.
Installing Docker Bash completion...
 % Total  % Received % Xferd Average Speed  Time  Time   Time Current
                 Dload Upload  Total  Spent  Left Speed
100 111k 100 111k  0   0  315k   0 --:--:-- --:--:-- --:--:-- 316k
docker-compose is already installed.
Package Installation is done
................Installing Registry service................
Traceback (most recent call last):
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
  httplib_response = self._make_request(
 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 395, in _make_request
  conn.request(method, url, **httplib_request_kw)
 File "/usr/lib/python3.10/http/client.py", line 1283, in request
  self._send_request(method, url, body, headers, encode_chunked)
 File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
  self.endheaders(body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
  self._send_output(message_body, encode_chunked=encode_chunked)
 File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
  self.send(msg)
 File "/usr/lib/python3.10/http/client.py", line 976, in send
  self.connect()
 File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
  sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied
```

Please fix this error.

**Comment by prasad-takale-eminds** [comment]
The issue is fixed. 
PR: https://github.com/beckn/beckn-utilities/pull/91

**Comment by vbabuEM** [comment]
This is still an issue. @prasad-takale-eminds , do you want to reopen this issue or open a new one.

**Comment by vbabuEM** [comment]
Since this issue is about the same problem, I will reopen it.

**Comment by vbabuEM** [comment]
Let me reverify before reopening this.
